<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT4R3UU1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT4R3UU1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT4R3UU1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT4R3UU1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT4R3UU1\App_KernelDevDebugContainer([
    'container.build_hash' => 'T4R3UU1',
    'container.build_id' => '03fec527',
    'container.build_time' => 1735906873,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT4R3UU1');
